# Generated by Django 6.0.4 on 2026-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_codigo_producto_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(default=9999, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateField(default='2026-05-01'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Wilson', max_length=30),
        ),
    ]
